# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: lucas
  password: Lts9406338
  host: localhost

development:
  <<: *default
  database: camaar_development

test:
  <<: *default
  database: camaar_test

production:
  <<: *default
  database: camaar_production
  username: lucas
  password: <%= ENV['DATABASE_PASSWORD'] %>

